### ISSUE TITLE
Idk if it's only for me but...

### ISSUE THREAD

**Issue by ghost** [scwmake/XCoder#1]
The ideal method for me for installing it would be:
1. Installing this repo as a zip
2. Extract
3. Running cmd in where it's installed
4. Running the XCoder command
It would then create ```Compression``` and ```SC-Textures``` folders upon running the XCoder command

The thing is that I need to delete those folders if I close the terminal then I repeat steps 3 & 4.

I don't really mind this, I am happy this actually works, but ig if anyone has issues then they should do this.

**Comment by Daniil-SV** [comment]
ok thanks for the idea
